name: Publish Package

on:
  push:
    tags:
      - 'v*' # 匹配所有以 "v" 开头的标签

jobs:
  publish:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}