name: Publish Package

on:
  push:
    tags:
      - 'v*' # 匹配所有以 "v" 开头的标签

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/' # 指定 npm 官方注册表

    - name: Install dependencies
      run: npm install
    
    - name: Fix package.json
      run: npm pkg fix # 修复 package.json

    - name: Debug npm config (可选)
      run: npm config list
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
